"""Static, escaped, source-driven documentation and roadmap builder."""
from pathlib import Path
from html import escape as e
import json, shutil, re
R=Path(__file__).resolve().parents[1]
OUT=R/'website/dist'
OUT.mkdir(parents=True,exist_ok=True)
issues=json.loads((R/'planning/issues.json').read_text())
nav='<a href="index.html">Grok Gadgets</a><nav><a href="start.html">Start here</a><a href="architecture.html">Architecture</a><a href="roadmap.html">Roadmap</a><a href="community.html">Community</a><a href="docs.html">Docs</a></nav>'
def page(name,title,body):
    (OUT/name).write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Independent open source gadgets exclusively for Grok. Honest local alpha documentation."><title>'+e(title)+' · Grok Gadgets</title><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">Skip to content</a><header>'+nav+'</header><main id="main">'+body+'</main><footer><span>Independent. Open source. Exclusively Grok.</span><a href="releases.html">Local release candidate</a><span>Apache-2.0 · 2026</span></footer><script src="motion.js" defer></script></body></html>')
def intro(k,title,desc):return '<p class="eyebrow">'+k+'</p><h1>'+title+'</h1><p class="lede">'+desc+'</p>'
board='''<div class="apparatus" aria-label="Diagram of the target AtomS3 Lite, simulation only"><div class="orbit"></div><div class="wire wire-a"></div><div class="wire wire-b"></div><div class="board"><span class="led"></span><span class="chip">C124<br>ESP32-S3</span><span class="button"></span><span class="usb">USB</span></div><span class="callout top">01 / RGB output</span><span class="callout bottom">02 / Button input</span><p class="diagram-label">ATOM S3 LITE · TARGET HARDWARE<br>SOFTWARE SIMULATION FIRST</p></div>'''
page('index.html','Home','''<section class="hero"><div>'''+intro('LOCAL ALPHA / 0.1','Give Grok<br>a physical world.','An open source toolkit for connecting devices, reading their state, and operating their capabilities through your existing Grok Bot.')+'''<a class="cta" href="start.html">Explore the local alpha <span>↗</span></a><p class="fine">Simulation available as local components complete.<br>Real Grok connectivity and physical hardware tests remain pending.</p></div>'''+board+'''</section><section class="statement"><p class="eyebrow">ONE ECOSYSTEM. FIVE REPOSITORIES.</p><h2>Build small.<br>Connect thoughtfully.</h2><p>For makers with an ESP32, developers on Linux, and homes already running Home Assistant. Self-hosted software with a clear boundary between a requested action and an observed result.</p></section><section class="paths"><a href="esp32.html"><span>01 / Makers</span><h3>ESP32</h3><p>AtomS3 Lite C124. USB first, LED and button. Compilation evidence stays separate from hardware verification.</p><b>Firmware & hardware ↗</b></a><a href="linux.html"><span>02 / Developers</span><h3>Linux</h3><p>Declare capabilities, handle commands, report state. A separately installable SDK for your own device application.</p><b>SDK & examples ↗</b></a><a href="home-assistant.html"><span>03 / Existing homes</span><h3>Home Assistant</h3><p>Reuse upstream MCP and exposed Assist entities. Preserve the controls your household already uses.</p><b>Integration recipe ↗</b></a></section><section>'''+intro('EVIDENCE, NOT PROMISES','Know what passed.','Simulated · Build verified · Grok verified · Hardware verified · Independently reproduced. Each describes a different observation.').replace('<h1>','<h2>').replace('</h1>','</h2>')+'''<a href="roadmap.html">See the current roadmap ↗</a></section>''')
page('start.html','Start here',intro('GETTING STARTED','Choose your first path.','Begin locally. No cloud account, payment, public endpoint, or physical board is required for the simulator.')+'''<ol class="steps"><li><h2>Run the simulator</h2><p>Open the sibling gateway repository. Follow its README to install the pinned environment and run its MCP acceptance demo. Test controls are explicitly separated from ordinary gadget tools.</p></li><li><h2>Build your own gadget</h2><p>Use the Linux capability API or compile the C124 firmware. Both consume protocol 0.1.0 from the gateway. <a href="linux.html">Linux guide</a> · <a href="esp32.html">ESP32 guide</a></p></li><li><h2>Connect your existing Grok Bot</h2><p>This gate remains open. Grok's cloud computer cannot launch a path on your Mac. Account testing and an approved authenticated reachable connection are prerequisites. No API conversation substitutes for the existing Bot.</p></li></ol>''')
page('esp32.html','ESP32',intro('HARDWARE / C124','A small board.<br>A precise contract.','Target: M5Stack AtomS3 Lite C124, built-in RGB LED and button, USB-C data cable.')+'''<p class="status">Hardware pending · exact compilation results recorded in the SDK evidence</p><h2>Build before you flash</h2><p>The separate ESP32 repository owns reusable firmware, board definitions, USB framing, toolchain pins, host tests, and recovery instructions. Read <code>../grok-gadgets-esp32-sdk/README.md</code> locally.</p><h2>Physical acceptance</h2><p>Observe green, another colour, and off; inspect real button press and release; unplug, reconnect, reboot, and check stale state. Firmware acknowledgement alone is not evidence that the LED illuminated.</p>''')
page('linux.html','Linux SDK',intro('SDK / LINUX','Your application.<br>Your capabilities.','Register a device, declare capabilities, handle commands, and report state and events without changing the gateway.')+'''<p class="status">Runtime evidence is platform-specific. macOS tests do not establish Linux support.</p><p>Read <code>../grok-gadgets-linux-sdk/README.md</code> for installation, the example device agent, reconnect behaviour, and systemd setup. The SDK owns application code; the gateway owns routing and canonical protocol.</p>''')
page('home-assistant.html','Home Assistant',intro('INTEGRATION / EXISTING HOMES','Start with what<br>your home already knows.','Reuse Home Assistant’s upstream MCP server and deliberately expose a small set of Assist entities.')+'''<p class="status">Fixture compatibility only until a real installation and Grok account are tested.</p><p>The sibling Home Assistant repository contains the setup recipe, read-only compatibility probe, fixtures, and limitations. Upstream endpoint <code>/api/mcp</code> uses Streamable HTTP and OAuth or bearer authentication. Event notifications are not currently supported by that integration.</p><p>Do not assume all entities or vendor functions are exposed. Existing local controls should continue working independently of a Grok conversation.</p>''')
page('architecture.html','Architecture',intro('SYSTEM / PROTOCOL 0.1.0','A command is<br>not an observation.','Keep assistant tools, routing, and device applications separate.')+'''<div class="flow"><span>Existing Grok Bot<br><small>Actual connection pending</small></span><b>↕ MCP</b><span>Gateway<br><small>Discovery · commands · state · events</small></span><b>↕ NDJSON</b><span>ESP32 / Linux<br><small>Execution reports</small></span></div><h2>Four distinct steps</h2><p><code>requested → accepted → device reports execution → physical effect observed</code></p><p>Device boot identity, bounded event history, cursor reset errors, timeouts, revocation, and explicit simulation status belong to the contract. The canonical schemas are owned by the gateway. Home Assistant may connect directly through upstream MCP.</p>''')
rows=''.join('<article class="issue"><span>'+e(i['id'])+' / '+e(i['milestone'])+'</span><h3>'+e(i['problem'])+'</h3><p class="status">'+e(i['stage'])+'</p><p>'+e(i.get('blocker') or ' · '.join(i['labels']))+'</p></article>' for i in issues)
page('roadmap.html','Roadmap',intro('SOURCE-DRIVEN / LOCAL ISSUE LEDGER','Work in the open.<br>Publish when ready.','Rendered from planning/issues.json. Local records become GitHub issues only after publication approval.')+'<div class="issue-list">'+rows+'</div>')
page('community.html','Community',intro('COMMUNITY / PREPARATION','Make room<br>for the next maker.','Technical records belong in GitHub once published. Community conversation can point to those canonical sources.')+'''<p><a href="https://www.reddit.com/r/GrokGadgets/">r/GrokGadgets ↗</a> is the intended community. No live settings or posts have been changed.</p><h2>Contribution recognition</h2><p>Opt in, prove ownership of both accounts, and verify an eligible merged contribution. Documentation and tests count. Matching usernames never establish identity. Local dry-run decisions do not award live flair.</p><h2>Community standards</h2><p>Be respectful, label verification honestly, protect household privacy, and share reproducible steps. Private reporting contacts and public repository destinations remain publication gates.</p>''')
page('releases.html','Releases',intro('RELEASE / LOCAL CANDIDATE','0.1.0-alpha.1','An unpublished local alpha candidate. Component versions and exact commits are recorded in compatibility/tested-components.json.')+'''<p>Gateway simulation, SDK contracts, firmware compilation, Home Assistant fixture compatibility, and community dry-run logic have separate evidence records. Consult the final local handoff before relying on any component.</p><p>Public release assets, repository owner, GitHub protections, website deployment, and Reddit changes require separate approval. Physical support and Grok desktop/mobile support remain unverified.</p><h2>Project activity</h2><p class="status">Unavailable — public repositories have not been created.</p><p>No fabricated stars, contributors, or issue counts are displayed as live activity. A bounded server-side data refresh adapter is prepared for later approved publication.</p>''')
# Canonical documents become safely escaped text pages, with preserved headings/content.
for src in [R/'CONTRIBUTING.md',R/'CODE_OF_CONDUCT.md',R/'SECURITY.md',*sorted((R/'docs').rglob('*.md')),*sorted((R/'community').rglob('*.md'))]:
    name='doc-'+str(src.relative_to(R)).replace('/','-').replace('.md','.html')
    page(name,src.stem,'<p class="eyebrow">CANONICAL SOURCE / '+e(str(src.relative_to(R)))+'</p><pre class="document">'+e(src.read_text())+'</pre>')
links=''.join('<li><a href="'+f.name+'">'+e(f.stem.removeprefix('doc-'))+'</a></li>' for f in sorted(OUT.glob('doc-*.html')))
page('docs.html','Documentation',intro('REFERENCE / LOCAL SOURCES','Read the source.','Documentation is generated from canonical hub files, with component instructions remaining in their own repositories.')+'<ul>'+links+'</ul>')
for f in ['style.css','motion.js']:shutil.copy(R/'website'/f,OUT/f)
# Validate local links and ensure generated assets are static.
from html.parser import HTMLParser
class Links(HTMLParser):
    def handle_starttag(self,tag,attrs):
        for k,v in attrs:
            if k in ['href','src'] and v and not v.startswith(('http:','https:','#','mailto:')):
                assert (OUT/v.split('#')[0]).is_file(),(self.file,v)
for f in OUT.glob('*.html'):
    parser=Links();parser.file=f.name;parser.feed(f.read_text())
print(f'Built and link-checked {len(list(OUT.glob("*.html")))} static pages')
